[package]
name = "p2s"
version = "0.1.0"
edition = "2021"

[dependencies]
clipp = "0.1.0"
comat = "0.1.3"
exoquant = "0.2.0"
fimg = "0.4.23"
mindus = { version = "5.0.9", path = "../mindus", default-features = false }
